### ISSUE TITLE
Is org.apache.camel.ExchangesInflight a counter?

### ISSUE THREAD

**Issue by tadayosi** [fabric8io-images/s2i#256]
See: https://github.com/fabric8io-images/s2i/blob/master/java/images/centos/prometheus-config.yml#L23
```yaml
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name="([^"]+)"><>ExchangesInflight'
    name: org.apache.camel.ExchangesInflight
    help: Exchanges Inflight
    type: COUNTER
    labels:
      context: $1
      type: context
```

I think it's rather a [gauge](https://prometheus.io/docs/concepts/metric_types/#gauge) in terms of Prometheus. Should we change it?

**Comment by tadayosi** [comment]
@astefanutti @cunningt @davsclaus
Can anyone confirm that please?

**Comment by tadayosi** [comment]
In a similar vein, isn't `org.apache.camel.Redeliveries` a counter instead of a gauge?
https://github.com/fabric8io-images/s2i/blob/master/java/images/centos/prometheus-config.yml#L217
```yaml
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>Redeliveries'
    name: org.apache.camel.Redeliveries
    help: Redeliveries
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
```
